<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface $board */
$board = $this->board;

/** @var \Eye4web\Zf2Board\Entity\TopicInterface[] $topics */
$topics = $this->topics;
?>
<h1><?=$board->getName()?></h1>
<a href="<?=$this->url('e4w/topic/create', ['board' => $board->getId()])?>"><?=$this->translate('Create new topic')?></a><br>
<br>

<?=$this->paginationControl($topics, 'sliding', ['eye4web-zf2-board/board/partials/paginator.phtml', 'Eye4web\Zf2Board'], [
    'route' => 'e4w/board/view',
    'params' => [
        'id' => $board->getId(),
        'slug' => $board->getSlug(),
    ]
]);?>

<table class="table">
    <thead>
        <tr>
            <th><?=$this->translate('Topic')?></th>
            <th><?=$this->translate('Author')?></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
    <?php foreach($topics as $topic) { ?>
        <tr>
            <td><?=$topic->getName()?></td>
            <td><?=$this->zf2BoardHelper()->getAuthor($topic->getUser())->getDisplayName()?></td>
            <td><a href="<?=$this->url('e4w/topic/view', ['id' => $topic->getId(), 'slug' => $topic->getSlug()])?>"><?=$this->translate('View topic')?></a></td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?=$this->paginationControl($topics, 'sliding', ['eye4web-zf2-board/board/partials/paginator.phtml', 'Eye4web\Zf2Board'], [
    'route' => 'e4w/board/view',
    'params' => [
        'id' => $board->getId(),
        'slug' => $board->getSlug(),
    ]
]);?>