anguage: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - ./.travis.install.sh

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Performance
  - php -n ./vendor/bin/phpunit --group=Performance
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly