language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Performance
  - php -n ./vendor/bin/phpunit --group=Performance
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/