<?php
/** @var \Eye4web\Zf2Board\Entity\BoardInterface $board */
$board = $this->board;

/** @var \Eye4web\Zf2Board\Entity\TopicInterface $topic */
$topic = $this->topic;

/** @var \Eye4web\Zf2Board\Entity\PostInterface[] $posts */
$posts = $this->posts;

/** @var \Eye4web\Zf2Board\Entity\PostInterface $topicPost */
$topicPost = $this->topicPost;

/** @var \Eye4web\Zf2Board\Form\Post\CreateForm $postForm */
$postForm = $this->postCreateForm;
?>
<h1><?=$board->getName()?> > <?=$topic->getName()?></h1>
<i><?=sprintf('Written by %s on %s.', $this->zf2BoardHelper()->getAuthor($topic->getUser())->getDisplayName(), $topic->getCreated()->format('Y/m/d H:i'))?></i><br>
<br>
<?=$topicPost->getText()?>
<br>
<?=$this->paginationControl($posts, 'sliding', ['eye4web-zf2-board/board/partials/paginator.phtml', 'Eye4web\Zf2Board'], [
    'route' => 'e4w/topic/view',
    'params' => [
        'id' => $topic->getId(),
        'slug' => $topic->getSlug(),
    ]
]);?>
<hr>

<?php foreach($posts as $post) { ?>
    <strong><?=$this->zf2BoardHelper()->getAuthor($post->getUser())->getDisplayName()?></strong><i>, <?=$post->getCreated()->format('Y/m/d H:i')?></i><br />
    <?php
    if (
            $this->zf2BoardHelper()->getAuth()->hasIdentity() &&
            $post->getUser() == $this->zf2BoardHelper()->getAuth()->getIdentity()->getId()
    ) {
    ?>
        <a href="<?=$this->url('e4w/post/edit', ['id' => $post->getId()])?>"><em><?=$this->translate('Edit')?></em></a> -
        <a href="<?=$this->url('e4w/post/delete', ['id' => $post->getId()])?>"><strong><?=$this->translate('Delete')?></strong></a><br />
    <?php } ?>
    <?=$post->getText()?>
    <hr />
<?php } ?>

<?=$this->paginationControl($posts, 'sliding', ['eye4web-zf2-board/board/partials/paginator.phtml', 'Eye4web\Zf2Board'], [
    'route' => 'e4w/topic/view',
    'params' => [
        'id' => $topic->getId(),
        'slug' => $topic->getSlug(),
    ]
]);?>

<?php if ($this->zf2BoardHelper()->getAuth()->hasIdentity() && !$topic->isLocked()) { ?>
<?=$this->form()->openTag($postForm)?>
<?=$this->formRow($postForm->get('text'))?><br />
<?=$this->formButton($postForm->get('submit')->setLabel('Post'))?>
<?=$this->formRow($postForm->get('csrf'))?>
<?=$this->form()->closeTag($postForm)?>
<?php } ?>
