<?php
/** @var \E4W\Zf2Board\Entity\BoardInterface[] $boards */
$boards = $this->boards;
?>
<table class="table">
    <thead>
        <tr>
            <th><?=$this->translate('Id')?></th>
            <th><?=$this->translate('Name')?></th>
            <th></th>
        </tr>
    </thead>

    <tbody>
    <?php foreach ($boards as $board) { ?>
        <tr>
            <td><?=$board->getId()?></td>
            <td><?=$board->getName()?></td>
            <td><a href="<?=$this->url('e4w/board/view', ['id' => $board->getId(), 'slug' => $board->getSlug()])?>"><?=$this->translate('View topics')?></a></td>
        </tr>
    <?php } ?>
    </tbody>
</table>